import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/services/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "UMKM Maju Indonesia Maju!",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <NextAuthProvider>
                <body className={`${inter.className} antialiased`}>
                    {children}
                </body>
            </NextAuthProvider>
        </html>
    );
}
